### ISSUE TITLE
Waiting room shows users even when empty

### ISSUE THREAD

**Issue by sbsmith86** [DoSomething/gladiator#131]
### background

When viewing a waiting room, after it has been split and the users removed, the waiting room show view is still showing users:

![screen shot 2016-03-22 at 4 44 04 pm](https://cloud.githubusercontent.com/assets/1700409/13967763/428345b4-f04f-11e5-8822-5ec372863b2e.png)

The problem is with the call to get the users in the `show()` method in the `WaitingRoomsController`

```
$users = $this->repository->getAll($room->users->pluck('id')->toArray());
```

`$room->users` returns an empty collection and when the `getAll()` method doesn't recieve anything, it just returns all users. 

### Solution

The `getAll()` method needs to be updated accept a `null` param and not return anything.

**Comment by weerd** [comment]
Just noting here:

For the solution, instead of updating the `getAll()` method to accept null, ended up updating the `show()` method on the `WaitingRoomsController` to check if any results before passing to the `getAll()`. The empty results in the controller was actually an empty array and not a value `null`, so it was causing the `getAll()` to retrieve _all_ users, which it's supposed to do if passed an empty array.
