### ISSUE TITLE
Implement laravel mail queue 

### ISSUE THREAD

**Issue by angaither** [DoSomething/gladiator#132]
add a mandrill send email functionality

(we can test/write this with some fake copy so it isn't blocked by #130)

**Comment by sbsmith86** [comment]
So this issue encompasses setting up mandrill as the mail driver and some sorta `sendEmail()` like method in the contest or competition controller that queues the messages for sending, and then like a button that sends the email?

**Comment by angaither** [comment]
@sbsmith86 yeah, if we should break this out into more issues, that's fine too.

**Comment by sbsmith86** [comment]
@angaither nah it's fine! This makes sense, just making sure I was understanding what was expected.

**Comment by sbsmith86** [comment]
Oh also wondering, for this first pass do we want like a button on the contest, that sends an email to all the competitions? Or a button on each competition that would have to be hit separately? 

Since competitions could be on different schedules, we probably want to kick them of individually, but if eventually we are moving to scheduling stuff, then we won't need that at all.

**Comment by angaither** [comment]
I would imagine that we want to kick them all off individually, because we would want to schedule them individually.
