### ISSUE TITLE
Old contests don't have all the emails set up

### ISSUE THREAD

**Issue by mikefantini** [DoSomething/gladiator#206]
https://qa-gladiator.dosomething.org/contests/27/messages/edit is missing "Leaderboard update 2 email"

**Comment by sbsmith86** [comment]
I am seeing this on dev as well. From what I can gather, some contests have messages set in the DB from like a 1st iteration of messages which are the same ones we are using now. 

Older contests have these messages set:

**labels**
`Leaderboard Update`
`Final Leaderboard Update`
`Reminder for first submission due`
`Reminder to submit v1`
`Reminder to submit v2`
`Last minute reminder v1`
`Last minute reminder v2`
`Welcome`

However in the `Correspondence` class where defaults are defined we have (assuming these got put in place after we added the messages above to the older contests)

`Welcome`
`Competition info`
`Where are you? Check status`
`Reminder for first submission due`
`Reminder for submission photo due`
`Almost over reminder`
`Last minute reminder`
`Leaderboard update`
`Leaderboard update 2`
`Final leaderboard update`

**Possible solutions**
On QA, I think we could just wipe and re-seed the DB so that it sets each contest with the newer messages, but there could be an impact on anything we have set up there already for testing purposes.

If this is a problem on Prod, we need a better solution...maybe a seeder that gets run once to update those old contests with the correct default message?

@weerd thoughts?

**Comment by weerd** [comment]
Yeah, I would say wipe and reseed QA, especially since now we have the capacity to also link _real_ staging campaigns instead of a bunch of fake numbers.  On Prod though, not sure. Might need to chat IRL... would need to potentially add an artisan command to repopulate those when missing?

**Comment by weerd** [comment]
I'm thinking a script that fills in missing stuff on Prod is i

**Comment by weerd** [comment]
sorry. pressed wrong button 😬

**Comment by weerd** [comment]
Damn it! Did it again!

**Comment by sbsmith86** [comment]
i'm down to chat about how to handle this IRL @weerd

**Comment by sbsmith86** [comment]
Chatted with @weerd I'm gonna add a command we can run to retroactively update default messages for old contests

So we would just run `php artisan updateDefaultMessages -override` to reset all messages to the defaults set in the `Correspondence` class. the `-override` option will allow us to specify even that for messages that are already in the DB, they need to be reset to the default. Running the command without the `-override` option will just add any new default messages that are missing without overriding any changes to other messages in the system.

**Comment by weerd** [comment]
👍

**Comment by weerd** [comment]
Chatted with Andrea IRL, we're not gonna worry about Contests with any of the messages missing, just updating the Contests with the latest defaults.

**Comment by mikefantini** [comment]
@weerd @angaither that's fine. We can always adjust leaderboard update 1 I guess to send out two leaderboard updates for WRWCTL. 

So are we closing this issue out then?

**Comment by weerd** [comment]
Nope. I'm working on a script to pop in the latest defaults for contests as we update the messaging. But my local dev is borked, so need to fix that first 😞
