### ISSUE TITLE
If there is no pro tip then "Pro tip - " shouldn't appear

### ISSUE THREAD

**Issue by mikefantini** [DoSomething/gladiator#217]
If pro tip field is blank then we should cut the whole pro tip line all together, not have "Pro tip - " and then blank space.

![image](https://cloud.githubusercontent.com/assets/6330971/14541735/64b241fa-0259-11e6-92e2-caa17cdf46bc.png)

**Comment by deadlybutter** [comment]
This is where the problem is atm https://github.com/DoSomething/gladiator/blob/aba3d6b7b9b155c1ee9455adae9fe5947047cfec/app/Http/Utilities/Correspondence.php#L82

`Pro tip - :pro_tip`

if `:pro_tip` is empty then we ignore it, but I'm not sure the best way to remove the `Pro tip -` part. 

I could do a string replace for it, but that means every time you include a pro tip in an email it has to start with Pro tip -. The alternative is we just add `:pro_tip` to the template, and dynamically add `Pro tip - ` in front of it if the tip is actually present.

**Comment by weerd** [comment]
Yeah, I believe that's where the issue is. I think the approach of removing this:
```
\n\rPro tip - :pro_tip:\n\r
``
and changing it to:
```
\n\r:pro_tip:
```

And then in the regex or whatever that pops in the pro tip it appends the `Pro tip - ` like you mention to the thing it populates, as well as adding the suffix for `\n\r`.

**Comment by angaither** [comment]
alternatively, we could require that Pro Tip field to include the words Pro Tip, if it's desired.

**Comment by weerd** [comment]
@angaither oh, like adding an attribute setter when the field gets saved to the DB?

**Comment by angaither** [comment]
@weerd also another idea, but yeah, I'm not sure if they _always_ want to say pro tip or if that field may be used for something else, like fun fact, or statistic it'd be weird to show this

```
// fun fact
Pro tip - kittens are the best kind of animal 
// stat
Pro tip - kittens are 99% more likely to beat a dog in a fight
```

so I meant more Chris/Hilary types out the entire thing. and we fill in just whatever has been placed in that field.

**Comment by mikefantini** [comment]
@angaither yeah let's go with that solution. Makes things less complicated *and* more flexible

**Comment by mikefantini** [comment]
Oh although I guess then we should use this issue to clean up the default text and remove "Pro tip -" from:

- Leaderboard update email
- Leaderboard update 2 email

**Comment by weerd** [comment]
Oh gotcha. Yeah, that'd prob be more versatile :)
