### ISSUE TITLE
Update the users page

### ISSUE THREAD

**Issue by angaither** [DoSomething/gladiator#234]
We should remove contestants section
it takes too long to load & I don't think it very useful

if we _really_ need a list of everyone, maybe this should be it's own view.

**Comment by weerd** [comment]
Maybe just reconsider what users show? Or have separate pages for Admin vs Staff vs Contestants. I also kinda want to add a new menu link for like "Development" or "Tools" or something that only shows for us devs to review logging or other useful info we could log to a view so that we don't have to SSH to get an idea of stuff for helping troubleshoot issues. Thoughts?

**Comment by deadlybutter** [comment]
I like the idea of making it ENV based.

Do we have an issue for user pagination as well? That could be an option + something we need to implement everywhere, not just (possibly) here.

**Comment by angaither** [comment]
@deadlybutter there's an issue for user pagination #95, but I think let's just remove this sub view from the main user page for now & make it a link to it's own page.
