### ISSUE TITLE
User search

### ISSUE THREAD

**Issue by angaither** [DoSomething/gladiator#253]
expose a user search box like aurora
`/v1/users/?search[]=``

**Comment by DFurnes** [comment]
Here's the [relevant docs](https://github.com/DoSomething/northstar/blob/dev/documentation/endpoints/users.md#retrieve-all-users). I've also been considering changing this endpoint to just be `?search=key` and have it just automatically search by all indexes  (rather than having to specify each index you want to use like `search[id]=key&search[email]=key&search[mobile]=key`). Anyone have thoughts/opinions?
