### ISSUE TITLE
set up phoenix & guzzle

### ISSUE THREAD

**Issue by angaither** [DoSomething/gladiator#28]

**Comment by weerd** [comment]
Mind elaborating on what this is, cause Guzzle is set up via `RestApiClient` class...

**Comment by angaither** [comment]
maybe we don't need this?
it was to support work for #26 & #27

**Comment by weerd** [comment]
yeah, I don't think we need this issue, cause Guzzle is pretty much set up via the `RestApiClass` (although it needs to likely get fleshed out a bit more). But #26 and #27 already indicate what needs to happen for those to work. This issue was just confusing cause not sure it adds anything to what those other 2 issues already indicate :)

**Comment by angaither** [comment]
:+1:
