### ISSUE TITLE
Return multiple users from search

### ISSUE THREAD

**Issue by sbsmith86** [DoSomething/gladiator#318]
Allow search to return multiple users. Bad judgement call on my part, i figured there wouldn't be two people with the same ID, email, or phone. While that may be true, it seems search can sometimes strip out info so that we aren't always searching for the exact email, for example, so multiple people might be returned.

**Comment by DFurnes** [comment]
This is totally a bug with the way we normalize data for each field in Northstar btw, not the Gladiator implementation (although agreed on a good quick fix being to return all fields). 😬 

I'm also still partial to modifying that parameter to just be a single `?search=term` like I mentioned in the [original issue](https://github.com/DoSomething/gladiator/issues/253), since in hindsight it seems a bit silly to have to specify the term for each index like this.

**Comment by sbsmith86** [comment]
@DFurnes +1 to modifying that param.
