### ISSUE TITLE
Mysterious missing contestants from contest waiting room

### ISSUE THREAD

**Issue by weerd** [DoSomething/gladiator#326]
The Contest [waiting room](https://gladiator.dosomething.org/contests/7) for the **Hot Dogs** contest seems to have had 118 (as of July 1, 2016) and then mysteriously dropped down to 93. All the missing users are valid contestants in the Gladiator DB with Northstar user account. Something seems to have happened where we dropped ~25 users from that particular waiting room.

This is something we should keep an eye on to see if it happens again and consider options for investigating what happened.

**Comment by ngjo** [comment]
Update from Chris For 9.14.16 -- this problem is still persisting:

- Looker reports 9,011 SFS opt ins, gladiator only captured 8,372. That's 639 engaged ppl who signed up for a comp that didn't get the experience.

**Comment by ngjo** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;rGt5a0nN&#x2F;31-as-a-developer-i-want-to-make-sure-all-people-who-have-signed-up-for-a-competition-is-making-it-into-the-waiting-room-so-that-pe"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> As a developer, I want to make sure all people who have signed up for a competition is making it into the waiting room so that people aren&#39;t left out.</a>
