### ISSUE TITLE
Split the waiting room

### ISSUE THREAD

**Issue by angaither** [DoSomething/gladiator#6]
After the signup dates in a waiting room has ended an admin needs to be able to split users out into competitions

**Comment by weerd** [comment]
This can potentially be worked on now that the seeds are working and assigning users to waiting rooms in PR #11.

Only other requirement is #5 for the Competition CRUD, but the method to split user can still be done :)

**Comment by deadlybutter** [comment]
> yeah, the controller should only be concerned with gathering info and showing it places. I was thinking it could be a method on the WaitingRoom model? also, we should probs discuss this in the corresponding issue ;)

- @weerd

**Comment by sbsmith86** [comment]
@weerd that was my thought as well.

**Comment by deadlybutter** [comment]
My current line of thinking is this, it might be too far out there for right now

- Send the client the total number of users in the waiting room, and the max cap per waiting room (eg: 300) 
- JS calculates on the client the default form / split (In order to avoid looping and CPU consumption on the server)
- Chris or whomever edits the form if they don't like the default split, and submits
- A queue in Laravel spawns up to update all of the users

**Comment by deadlybutter** [comment]
ok ignore all of this ^ -- more than we need for this v1 app
